Revert "Reland "Enable -Wextra-semi in release builds that don't set dcheck_always_on=true.""
This reverts commit 5216f4babf120302852acf696a55b2c432c2cfdc.

Reason for revert: Causes ios-device-xcode-clang compile to fail:

  ../../base/synchronization/atomic_flag.h:43:42: error: extra ';' inside a class [-Werror,-Wextra-semi]
    SEQUENCE_CHECKER(set_sequence_checker_);

  ../../base/memory/weak_ptr.h:112:40: error: extra ';' inside a class [-Werror,-Wextra-semi]
      SEQUENCE_CHECKER(sequence_checker_);

Original change's description:
> Reland "Enable -Wextra-semi in release builds that don't set dcheck_always_on=true."
> 
> The original change broke the iOS build because one Objective-C class used
> SEQUENCE_CHECKER(), and static_assert() is currently not allowed in Objective-C
> code. So don't enable -Wextra-semi for Objective-C code and don't expand
> it to static_assert for now, until (if?) the compiler allows this.
> 
> Original change's description:
> > Revert "Enable -Wextra-semi in release builds that don't set dcheck_always_on=true."
> >
> > This reverts commit f6fa5cac2d777af3b53bf3ed699cd1da906664c8.
> >
> > Reason for revert: broke https://ci.chromium.org/p/chromium/builders/ci/ios-device/116376
> >
> > Original change's description:
> > > Enable -Wextra-semi in release builds that don't set dcheck_always_on=true.
> > >
> > > Most of these are macros that expand to nothing when dchecks are off, but
> > > to a declaration when dchecks are on. They are meant to be used to declare
> > > member variables.
> > >
> > > Since clang-format gets very confused on class member declarations that
> > > don't end in a semicolon and since we require clang-formatting,
> > > we need some way to still permit a semicolon after these macros even
> > > with dchecks off. To that end, add a dummy static_assert() at the end
> > > of these macros.
> > >
> > > Alternatively, we could surround all uses of these macros with explicit
> > > DCHECK_IS_ON() checks.
> > >
> > > Depends on https://skia-review.googlesource.com/c/skia/+/196421
> > >
> > > TBR=dalecurtis
> > >
> > > Bug: 926235,936856
> > > Change-Id: I66ab08f383b2f27dc6a7617f67f33fa66ddfa00c
> > > Reviewed-on: https://chromium-review.googlesource.com/c/1495041
> > > Commit-Queue: Nico Weber <thakis@chromium.org>
> > > Reviewed-by: Gabriel Charette <gab@chromium.org>
> > > Cr-Commit-Position: refs/heads/master@{#636838}
> >
> > TBR=dalecurtis@chromium.org,gab@chromium.org,thakis@chromium.org
> >
> > Change-Id: Iba14b13129b16b569249e62afa4644209e1435c6
> > No-Presubmit: true
> > No-Tree-Checks: true
> > No-Try: true
> > Bug: 926235, 936856
> > Reviewed-on: https://chromium-review.googlesource.com/c/1496308
> > Reviewed-by: Nico Weber <thakis@chromium.org>
> > Commit-Queue: Nico Weber <thakis@chromium.org>
> > Cr-Commit-Position: refs/heads/master@{#636850}
> 
> TBR=dalecurtis@chromium.org,gab@chromium.org,thakis@chromium.org
> 
> # Not skipping CQ checks because original CL landed > 1 day ago.
> 
> Bug: 926235, 936856
> Change-Id: Ic6bd087026e8ba257862da1c493d9d54a5ca816d
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1511734
> Commit-Queue: Nico Weber <thakis@chromium.org>
> Reviewed-by: Nico Weber <thakis@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#639189}

TBR=dalecurtis@chromium.org,gab@chromium.org,thakis@chromium.org

Change-Id: Ibf7a24a6fcda64abaa346eb60cfd959fd5ede5e4
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 926235, 936856
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1512699
Reviewed-by: Robert Liao <robliao@chromium.org>
Commit-Queue: Robert Liao <robliao@chromium.org>
Cr-Commit-Position: refs/heads/master@{#639204}

CrOS-Libchrome-Original-Commit: 09277d5c5b971a488c4d9e71f14b6e04ec872409