Fix StrongAlias (de)serialization in IPC messages.
It currently uses
param_type::StrongAlias(..) to construct the type, which seems wrong
as param_type = util::StrongAlias<TagType, UnderlyingType>.
Which causes following compile error:

In file included from ../../ipc/ipc_message_utils_unittest.cc:5:
../../ipc/ipc_message_utils.h:1075:10: error: missing 'typename' prior to dependent type name 'param_type::StrongAlias'
    *r = param_type::StrongAlias(value);
         ^~~~~~~~~~~~~~~~~~~~~~~
Call StrongAlias constructor directly to fix this.
Add a regression unit test to fix the regression.

Bug: None
Change-Id: If172c83abd22498117c47a8721b7d9057c18a1d9
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1983570
Reviewed-by: Ken Rockot <rockot@google.com>
Commit-Queue: Istiaque Ahmed <lazyboy@chromium.org>
Cr-Commit-Position: refs/heads/master@{#728702}


CrOS-Libchrome-Original-Commit: 4832b03bf6036dd7a7f2c0ab0cb5a0c3f907b43b