Revert "Reland "Remove the old version of PolicyMap::Set""
This reverts commit f4832bba09e94f96fd36c07518fdaf05bc0b1564.

Reason for revert: Chrome branded builds are breaking. First breakage
was https://ci.chromium.org/p/chrome/builders/ci/win64-trunk/51134

Error is:

FAILED: obj/chrome/test/unit_tests/metrics_reporting_handler_unittest.obj
c:\b\s\w\ir\cache\goma\client\gomacc.exe ..\..\third_party\llvm-build\Release+Asserts\bin\clang-cl.e...(too long)
../../chrome/browser/ui/webui/settings/metrics_reporting_handler_unittest.cc(108,10): error: no matching member function for call to 'Set'
map()->Set(policy::key::kMetricsReportingEnabled,

This file is only compiled for official builds so that's why it was
missed.

Original change's description:
> Reland "Remove the old version of PolicyMap::Set"
> 
> This is a reland of 9b84489c92fb4c2eab26548dd1f6b0ee8c78c030
> after fixing google_update_policy_fetcher_win.cc
> 
> Original change's description:
> > Remove the old version of PolicyMap::Set
> >
> > 1. Removed the old version of PolicyMap::Set,
> > which passes value as unique_ptr.
> > 2. Changed all the remaining refs use the new
> > version which passes value parameter as base::Value
> > instead of unique_ptr.
> >
> > Bug: 1092469
> > Change-Id: Ie45bb05b603cedcad8119a65134c4f5f008964dc
> > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2332191
> > Reviewed-by: Avi Drissman <avi@chromium.org>
> > Reviewed-by: Eugene But <eugenebut@chromium.org>
> > Reviewed-by: Maksim Ivanov <emaxx@chromium.org>
> > Commit-Queue: Aya Elsayed <ayaelattar@chromium.org>
> > Cr-Commit-Position: refs/heads/master@{#795078}
> 
> Bug: 1092469
> Change-Id: I4dfdf57753377ca49a6965b416e2a88c306f2ec7
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2339958
> Reviewed-by: Maksim Ivanov <emaxx@chromium.org>
> Reviewed-by: Avi Drissman <avi@chromium.org>
> Reviewed-by: Eugene But <eugenebut@chromium.org>
> Commit-Queue: Aya Elsayed <ayaelattar@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#795338}

TBR=avi@chromium.org,eugenebut@chromium.org,emaxx@chromium.org,ayaelattar@chromium.org

Change-Id: I66eeda5d032bcbf1d8e3628690e38911dbc5dd13
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 1092469
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2341817
Reviewed-by: Bruce Dawson <brucedawson@chromium.org>
Commit-Queue: Bruce Dawson <brucedawson@chromium.org>
Cr-Commit-Position: refs/heads/master@{#795628}


CrOS-Libchrome-Original-Commit: 4c2f977bf45aac4445e0fdd37d007db32e0ba7ed