Avoid using try-with-resources on ZipFile.
ZipFile does not implement Closeable interface prior to api19:
https://developer.android.com/sdk/api_diff/19/changes/java.util.zip.ZipFile
It was introduced as a fix for failed library extraction here:
https://chromium-review.googlesource.com/c/chromium/src/+/930332
So, this code gets executed quite rare, but I can see some
"java.lang.IncompatibleClassChangeError: interface not implemented" errors
on our radars at Yandex, mostly Huawei 4.1.2, 4.2.* and 4.3.*. Since
non-googlers don't have access to crash tickets, I can't check if Chrome
has same issues, but I believe that you have.

This CL adds a custom closeQuietly method for ZipFile, and rewrites a
try-with-resources statement with it. Docs say that ZipFile.close() also
closes all the streams, so I removed InputStream from try as well:
https://developer.android.com/reference/java/util/zip/ZipFile.html#close().

R=agrieve@chromium.org,ranj@chromium.org

Change-Id: I6b626bf87f01f5598ab61be3ac88759b4c7076e2
Reviewed-on: https://chromium-review.googlesource.com/1156397
Reviewed-by: agrieve <agrieve@chromium.org>
Commit-Queue: agrieve <agrieve@chromium.org>
Cr-Commit-Position: refs/heads/master@{#580224}

CrOS-Libchrome-Original-Commit: 958e526c6eb57b74c82fd43eb94512b848f01bd9