Roll src/third_party/googletest/src/ 5395345ca..306f3754a (123 commits)
https://chromium.googlesource.com/external/github.com/google/googletest.git/+log/5395345ca4f0..306f3754a71d

$ git log 5395345ca..306f3754a --date=short --no-merges --format='%ad %ae %s'
2019-12-30 absl-team Googletest export
2019-12-30 absl-team Googletest export
2019-12-26 absl-team Googletest export
2019-12-19 absl-team Googletest export
2019-12-18 absl-team Googletest export
2019-12-18 absl-team Googletest export
2019-12-20 kontakt Make move operation noexcept.
2019-12-20 kontakt Define default destructor for test classes
2019-12-20 kontakt Deleted functions as part of public interface
2019-12-20 kontakt Review notes: Return T& from assignment operators
2019-12-17 kontakt Disable move constructor and assignment operator for test classes.
2019-12-16 krzysio Googletest export
2019-12-10 syoussefi Revert "Googletest export": disallow empty prefix
2019-12-10 syoussefi Revert "Googletest export": Remove test for empty prefix
2019-12-16 syoussefi Workaround VS bug w.r.t empty arguments to macros
2019-12-12 absl-team Googletest export
2019-12-11 absl-team Googletest export
2019-12-10 absl-team Googletest export
2019-12-06 misterg Googletest export
2019-12-13 kravlala.1 Activate GNU extensions in case of MSYS generator
2019-12-05 absl-team Googletest export
2019-12-05 absl-team Googletest export
2019-12-05 absl-team Googletest export
2019-12-02 absl-team Googletest export
2019-11-27 krystian.kuzniarek Revert "remove MSVC workaround: wmain link error in the static library"
2019-11-27 krystian.kuzniarek Revert "unify googletest and googlemock main functions"
2019-11-27 Oleksandr.Yefremov Rename test case to test suite
2019-11-26 absl-team Googletest export
2019-11-25 absl-team Googletest export
2019-11-25 mate.pek README.md: added Catch2 and Google Test Explorer
2019-11-25 maximilianschwab Fixed typo
2019-11-22 absl-team Googletest export
2019-11-20 absl-team Googletest export
2019-11-17 krystian.kuzniarek unify googletest and googlemock main functions
2019-11-17 krystian.kuzniarek remove MSVC workaround: wmain link error in the static library
2019-11-22 krystian.kuzniarek remove Nokia's Symbian compiler workaround: SafeMatcherCastImpl
2019-11-22 krystian.kuzniarek consistency fix for SafeMatcherCastImpl member functions
2019-11-17 krystian.kuzniarek remove MSVC workaround: cease const dropping
2019-11-17 krystian.kuzniarek remove MSVC workaround: warning 4355
2019-11-14 krystian.kuzniarek remove MSVC workaround: error C2665
2019-11-14 krystian.kuzniarek remove MSVC workaround: accessing namespace scope from within nested classes
2019-11-22 krystian.kuzniarek remove stale comments about older GCC versions
2019-11-22 krystian.kuzniarek remove g++ 2.95.0 workaround: no space after first comma in macros
2019-11-22 krystian.kuzniarek remove g++ 3.3 workaround: using on operator<<
2019-11-21 Christoph.Strehle Fix compile break for Microsoft Visual Studio 2017 v141
2019-11-19 absl-team Googletest export
2019-11-18 absl-team Googletest export
2019-11-16 xyb Fix internal memory leak in Windows _Crt report.
2019-11-15 b.gianfo Fix FlatTuple compilation on older msvc.
2019-11-08 absl-team Googletest export
(...)
2019-10-25 piotrwn1 Apply 80chars limit
2019-10-24 piotrwn1 Tests simplified and names corrected (POD->scalar)
2019-09-10 krystian.kuzniarek remove BiggestInt
2019-10-23 absl-team Googletest export
2019-10-23 joshdcannon Revert "Merge pull request #2498 from thejcannon:noexcept_spec"
2019-10-22 absl-team Googletest export
2019-10-22 absl-team Googletest export
2019-10-23 piotrwn1 Added more tests to verify: ReturnRef not accept temporary
2019-10-22 piotrwn1 Added tests verifying that temporaries are accepted by ReturnRef
2019-10-22 absl-team Googletest export
2019-10-22 piotrwn1 Prevent using ReturnRef on reference to temporary
2019-10-21 absl-team Googletest export
2019-10-18 absl-team Googletest export
2019-10-19 41349879+cloudrex Remove extra space
2019-10-18 dieter.gnaier Fix Issue 2418
2019-10-18 misterg Googletest export
2019-10-17 absl-team Googletest export
2019-10-17 absl-team Googletest export
2019-10-17 lesha [googletest] Output skip message
2019-10-16 absl-team Googletest export
2019-10-11 joshdcannon Avoid recursive macros
2019-10-09 robert Add more override keywords
2019-10-07 chrisjohnsonmail Update to distinguish prelease purpose of this fork.
2019-10-11 joshdcannon Removing extraneous parenthesis
2019-10-11 joshdcannon Evaluate and cat NARG in different macros
2019-08-29 chrisjohnsonmail Add ESP8266 configs to PlatformIO build
2019-08-28 chrisjohnsonmail feat: Add support for ESP8266 platform
2019-10-11 joshdcannon Removing extraneous test
2019-10-11 joshdcannon Replace compile-test with preprocessor test
2019-10-11 joshdcannon Fix preprocessor tests
2019-10-11 joshdcannon Add a compile test
2019-10-11 joshdcannon Workaround MSVC VA_ARGS weirdness
2019-10-11 misterg Googletest export
2019-10-10 absl-team Googletest export
2019-10-10 absl-team Googletest export
2019-10-11 krystian.kuzniarek clean-up broken paths for PlatformIO
2019-10-10 chrisjohnsonmail chore:  update version
2019-10-10 joshdcannon Made noexcept condition more exciting
2019-10-09 absl-team Googletest export
2019-10-09 zeb Mention Cornichon as a related open source project
2019-10-07 joshdcannon Use declval in noexcept expression
2019-10-07 joshdcannon Switch to free function to avoid GCC bug
2019-10-07 joshdcannon Avoid comma operator
2019-10-07 joshdcannon Fix spacing
2019-10-07 joshdcannon Use the verbatim noexcept spec in MOCKED_METHOD
2019-09-05 krystian.kuzniarek remove GTEST_ARRAY_SIZE_
2019-08-22 krystian.kuzniarek mention the existing support for wide strings in string matchers
2019-08-22 krystian.kuzniarek change usings
2019-09-10 krystian.kuzniarek change includes in gtest-port.h
2019-09-10 krystian.kuzniarek remove GTEST_HAS_STD_STRING
2019-09-10 krystian.kuzniarek remove a dead function
Created with:
  roll-dep src/third_party/googletest/src

Cq-Include-Trybots: luci.chromium.try:android_optional_gpu_tests_rel,mac_optional_gpu_tests_rel
Bug: 1023677, 1039450
Change-Id: I17509b0e81b34f33e9f210042aa462da55578913
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1955786
Reviewed-by: Patrik Höglund <phoglund@chromium.org>
Reviewed-by: Mohammad Refaat <mrefaat@chromium.org>
Reviewed-by: Erik Chen <erikchen@chromium.org>
Reviewed-by: Victor Costan <pwnall@chromium.org>
Commit-Queue: Ilia Samsonov <isamsonov@google.com>
Cr-Commit-Position: refs/heads/master@{#732289}


CrOS-Libchrome-Original-Commit: 27a518129a16c6d7986435da191892814dbdd84f