GCC: make base::FilePath move assignment operator noexcept
The move assignment operator in PaintPreviewClient::PaintPreviewData is
noexcept. Because this class has a member of type base::FilePath, the
move assignment operator of base::FilePath must be noexcept too.

Otherwise GCC fails like this:

../../components/paint_preview/browser/paint_preview_client.cc:107:1:

error: function 'paint_preview::PaintPreviewClient::PaintPreviewData&
paint_preview::PaintPreviewClient::PaintPreviewData::operator=
(paint_preview::PaintPreviewClient::PaintPreviewData&&)' defaulted on
its redeclaration with an exception-specification that differs from
the implicit exception-specification ''
  107 | PaintPreviewClient::PaintPreviewData::operator=(
      | ^~~~~~~~~~~~~~~~~~

Bug: 819294
Change-Id: I87b88a81e8af6b7e61f0d1a8c8444fd6707e50d2
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2218168
Commit-Queue: Lei Zhang <thestig@chromium.org>
Reviewed-by: Lei Zhang <thestig@chromium.org>
Cr-Commit-Position: refs/heads/master@{#772348}


CrOS-Libchrome-Original-Commit: c65b4d03c76da607b6b678c4a46baa75ca0cf7b3