Revert "base/power_monitor: Add method to query thermal state"
This reverts commit 1e56c5516037e023060ec7d27586a1b1dade0ee2.

Reason for revert: Broke compile on Mac Builder (dbg)

Failure
Step compile failed. Error logs are shown below:
[724/7143] CXX obj/base/base_unittests/power_monitor_device_source_unittest.o
FAILED: obj/base/base_unittests/power_monitor_device_source_unittest.o
/b/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF...(too long)
../../base/power_monitor/power_monitor_device_source_unittest.cc:32:3: error: use of undeclared identifier 'DVLOG'
DVLOG(1) << PowerMonitorSource::DeviceThermalStateToString(current_state);
^
1 error generated.
More information in raw_io.output[failure_summary]

Original change's description:
> base/power_monitor: Add method to query thermal state
> 
> wip wip
> 
> Add PowerMonitor::GetCurrentThermalState()
> 
> Bug: 1071431
> Change-Id: Id3083e06f16fd2f05e685e77ddee94e274158758
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2248729
> Reviewed-by: Henrik Boström <hbos@chromium.org>
> Reviewed-by: François Doray <fdoray@chromium.org>
> Commit-Queue: Miguel Casas <mcasas@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#781322}

TBR=fdoray@chromium.org,mcasas@chromium.org,hbos@chromium.org

Change-Id: I54bbdc02423890b8443cb2f1deec909b68d87ebf
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 1071431
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2260792
Reviewed-by: Chris Sharp <csharp@chromium.org>
Commit-Queue: Chris Sharp <csharp@chromium.org>
Cr-Commit-Position: refs/heads/master@{#781325}


CrOS-Libchrome-Original-Commit: cae845749cbad44bc7f0ade05ff94ec616381f8b