Revert "[TaskEnvironment] Standardize paradigm for classes forwarding traits"
This reverts commit 7472b906ce9d41171b9eabe807fc210072fdc2e9.

Reason for revert: sheriff suspects this caused a build break on win{,32}-archive-rel:

https://ci.chromium.org/p/chromium/builders/ci/win-archive-rel/4309

In file included from ../../chrome/chrome_cleaner/ipc/proto_chrome_prompt_ipc_unittest.cc:14:
In file included from ../..\base/test/scoped_task_environment.h:15:
In file included from ../..\base/task/lazy_task_runner.h:17:
../..\base/task/task_traits.h(263,5): error: static_assert failed due to requirement 'has_thread_pool ^ has_extension' "Traits must explicitly specify a destination (e.g. ThreadPool or a named thread like BrowserThread)"
    static_assert(
    ^
../..\chrome/chrome_cleaner/ipc/proto_chrome_prompt_ipc.h(108,39): note: in instantiation of function template specialization 'base::TaskTraits::TaskTraits<base::MayBlock, void>' requested here
      base::CreateSequencedTaskRunner({base::MayBlock()});
                                      ^
1 error generated.

Original change's description:
> [TaskEnvironment] Standardize paradigm for classes forwarding traits
> 
> As discussed @
> https://chromium-review.googlesource.com/c/chromium/src/+/1749538/6/ash/test/ash_test_base.h#84
> 
> Usage of explicit everywhere also avoids implicit copy construction
> and is the reason for changes to a few unit tests that previously
> used operator= to initialize their task environments.
> 
> TBR=dcheng@chromium.org
> (for widespread mechanical change)
> 
> Bug: 992483
> Change-Id: I321576674f3b387a6f5069e8e71eebf41c98e7ed
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1758338
> Reviewed-by: Gabriel Charette <gab@chromium.org>
> Reviewed-by: Daniel Cheng <dcheng@chromium.org>
> Commit-Queue: Gabriel Charette <gab@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#689098}

TBR=dcheng@chromium.org,gab@chromium.org

Change-Id: I69b71b220ab583bc3a18e8fb07213fa1b6a75b50
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 992483
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1762475
Reviewed-by: Elly Fong-Jones <ellyjones@chromium.org>
Commit-Queue: Elly Fong-Jones <ellyjones@chromium.org>
Cr-Commit-Position: refs/heads/master@{#689122}


CrOS-Libchrome-Original-Commit: eb6516975fc26fc14b10b027482a62f0a4606fa9