mojo: Add the size template parameter to ArrayTraits<base::span>
The ArrayTraits specialization for base::span with a specified size was
considered to be missing. This caused accessors in mojom traits that
returned a base::span with a specified size to fail to compile with:

error: static_assert failed due to requirement 'internal::AlwaysFalse<span<const unsigned char, 6> >::value' "Cannot find the mojo::ArrayTraits specialization. Did you forget to include the corresponding header file?"
Change-Id: I61ab07f2a1f74ea2eb5073b2776c995ce86b6255
Reviewed-on: https://chromium-review.googlesource.com/c/1356159
Commit-Queue: Giovanni Ortuño Urquidi <ortuno@chromium.org>
Reviewed-by: Ken Rockot <rockot@google.com>
Reviewed-by: Sam McNally <sammc@chromium.org>
Cr-Commit-Position: refs/heads/master@{#612529}

CrOS-Libchrome-Original-Commit: a1b952115baf8e9e0ba6393d38363724a65bd220