Revert "Remove the old version of PolicyMap::Set"
This reverts commit 9b84489c92fb4c2eab26548dd1f6b0ee8c78c030.

Reason for revert: breaks windows compile

Looks like we missed a callsite here:
https://source.chromium.org/chromium/chromium/src/+/master:chrome/browser/google/google_update_policy_fetcher_win.cc;l=37;drc=0103fe2cf95d7e8fc1a46633d30f56131228906c

[46403/48688] CXX obj/chrome/browser/browser/google_update_policy_fetcher_win.obj
FAILED: ../../chrome/browser/google/google_update_policy_fetcher_win.cc /Foobj/chrome/browser/browser/google_update_policy_fetcher_win.obj /Fd"obj/chrome/browser/browser_cc.pdb"
../../chrome/browser/google/google_update_policy_fetcher_win.cc(37,13): error: no matching member function for call to 'Set'
policies->Set(policy_name, policy::POLICY_LEVEL_MANDATORY,
~~~~~~~~~~^~~
../..\components/policy/core/common/policy_map.h(146,8): note: candidate function not viable: no known conversion from 'typename remove_reference<unique_ptr<Value, default_delete<Value>> &>::type' (aka 'std::__1::unique_ptr<base::Value, std::__1::default_delete<base::Value>>') to 'base::Optional<base::Value>' for 5th argument
void Set(const std::string& policy,
^
../..\components/policy/core/common/policy_map.h(153,8): note: candidate function not viable: requires 2 arguments, but 6 were provided
void Set(const std::string& policy, Entry entry);
^
1 error generated.


Original change's description:
> Remove the old version of PolicyMap::Set
> 
> 1. Removed the old version of PolicyMap::Set,
> which passes value as unique_ptr.
> 2. Changed all the remaining refs use the new
> version which passes value parameter as base::Value
> instead of unique_ptr.
> 
> Bug: 1092469
> Change-Id: Ie45bb05b603cedcad8119a65134c4f5f008964dc
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2332191
> Reviewed-by: Avi Drissman <avi@chromium.org>
> Reviewed-by: Eugene But <eugenebut@chromium.org>
> Reviewed-by: Maksim Ivanov <emaxx@chromium.org>
> Commit-Queue: Aya Elsayed <ayaelattar@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#795078}

TBR=avi@chromium.org,eugenebut@chromium.org,emaxx@chromium.org,ayaelattar@chromium.org

Change-Id: I03456080e9878bcc82eda2eddfe6474b8b13fed2
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 1092469
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2339389
Reviewed-by: Devlin <rdevlin.cronin@chromium.org>
Commit-Queue: Devlin <rdevlin.cronin@chromium.org>
Cr-Commit-Position: refs/heads/master@{#795092}


CrOS-Libchrome-Original-Commit: 7380858cdf66b0a06a3312afd1798d7c82d0b3b5