IWYU: std::vector used in base/cpu.h requires vector include
Build with libstdc++ fails:
../../base/cpu.h:93:15: error: ‘vector’ in namespace ‘std’ does not name a template type
   93 |   static std::vector<CoreType> GuessCoreTypes();

Bug: 957519
Change-Id: I83808e1714146c6fa1dbefea205620c600b32e48
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2339339
Reviewed-by: Wez <wez@chromium.org>
Commit-Queue: José Dapena Paz <jdapena@igalia.com>
Cr-Commit-Position: refs/heads/master@{#795393}


CrOS-Libchrome-Original-Commit: 91fce6f2d4a659c3b2fadbe8413d031f8877902a