Revert "Reland "New toolchain for Windows 10 19041 SDK""
This reverts commit 424526a023397ebbe6555ea27b82f66c137e8022.

Reason for revert: win64-chrome build succeeded (progress) but
win32-chrome builder failed with a previously unseen error, shown
here:

[170/58214] ACTION //remoting/host/win:remoting_lib_idl_idl_action(//build/toolchain/win:win_clang_x86)
FAILED: gen/remoting/host/win/chromoting_lib.h gen/remoting/host/win/chromoting_lib.dlldata.c gen/remoting/host/win/chromoting_lib_i.c gen/remoting/host/win/chromoting_lib_p.c gen/remoting/host/win/chromoting_lib.tlb 
c:\b\s\w\ir\cipd_bin_packages\cpython\bin\python.exe ../../build/toolchain/win/midl.py environment.x86 c:/b/s/w/ir/cache/builder/src/third_party/win_build_output/midl/remoting/host/win gen/remoting/host/win 7219b935-4873-533b-9ce1-20c9e9b12def chromoting_lib.tlb chromoting_lib.h chromoting_lib.dlldata.c chromoting_lib_i.c chromoting_lib_p.c gen/remoting/host/win/chromoting_lib.idl /char signed /env win32 /Oicf
cl : Command line error D8027 : cannot execute 'c:\b\s\w\ir\cache\builder\src\third_party\depot_tools\win_toolchain\vs_files\a687d8e2e4114d9015eb550e1b156af21381faac\win_sdk\bin\..\..\VC\Tools\MSVC\14.26.28801\bin\HostX64\x86\c1.dll'
midl : command line error MIDL1003 : error returned by the C preprocessor (2)

Original change's description:
> Reland "New toolchain for Windows 10 19041 SDK"
> 
> This is a reland of 4a4f53a7f22f9058b2f171fc46bc5657bbe83e45
> 
> The original patch would fail to build on the mksnapshot step on
> Windows 7 (and server equivalents). This was due to two APISet DLLs
> that are required for the new dbghelp.dll. This change copies the two
> of them during gn gen. In order to have them as part of the isolates
> for cdb and in order to avoid dangerous ambiguity they are now
> required, which means that when this change lands the new SDK will be
> required. This is slightly disruptive for developers who aren't using
> our toolchain, but it seems unavoidable.
> 
> Developers who don't have the latest SDK installed will hit this error
> message during gn gen:
> 
>  Exception: api-ms-win-downlevel-kernel32-l2-1-0.dll not found in "..."
>  You must install the "Debugging Tools for Windows" feature from the
>  Windows 10 SDK, the 10.0.19041.0 version.
> 
> Original change's description:
> > New toolchain for Windows 10 19041 SDK
> >
> > This change updates the toolchain package used to build Chromium with
> > the 10.0.19041.0 (2020-04) SDK and VS 16.6.1. The d3dcompiler_47.dll
> > DLLs for x86 and x64 were swapped out for the 10.0.17134 versions (as
> > usual).
> >
> > The Debuggers directory was not swapped out this time because the
> > problem with loading dbghelp.dll on Windows 7
> > (https://crbug.com/1021650) has been resolved.
> >
> > The output for the cdb copy step was updated because one additional UCRT
> > DLL is now copied.
> >
> > Packaging was done on a Windows Server 2019 VM, cleanly created for this
> > purpose.
> >
> > The package was created by downloading the VS Professional 2019
> > installer from https://visualstudio.microsoft.com/downloads/
> > (free trial, not preview) and then running the installer like this:
> >
> > $ PATH_TO_INSTALLER.EXE ^
> >     --add Microsoft.VisualStudio.Workload.NativeDesktop ^
> >     --add Microsoft.VisualStudio.Component.VC.ATLMFC ^
> >     --add Microsoft.VisualStudio.Component.VC.Tools.ARM64 ^
> >     --add Microsoft.VisualStudio.Component.VC.MFC.ARM64 ^
> >     --includeRecommended --passive
> >
> > Then the latest Windows 10 SDK was downloaded and installed from
> > https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk/
> >
> > Then the packaging script was run like this:
> >
> >   python3 depot_tools\win_toolchain\package_from_installed.py 2019 -w 10.0.19041.0
> >
> > Since the new d3dcompiler_47.dll uses the UCRT and we want to avoid
> > shipping that (https://crbug.com/920704) the final packaging step was to
> > unzip the package, copy over the two copies of that DLL from the
> > previous toolchain's win_sdk\Redist, and then repackage the toolchain
> > with:
> >   > python3 package_from_installed.py --repackage=<full-path-to-toolchain-dir>
> >
> > UWP and ARM64 support and Python 3 compatibility were previously added
> > to package_from_installed.py.
> >
> > Future changes will require the new SDK, but for now the previous SDK
> > can also be used to build Chromium.
> >
> > The failures on the win*msvc* bots are unrelated. This was proven by
> > creating crrev.com/c/2245914 which is a NOP toolchain test. The existing
> > toolchain was repackaged with a single text file added and that caused
> > identical failures.
> >
> > Bug: 920704, 1014701, 1021650, 1089996
> > Change-Id: Ie496354582458aa8c1292ed4ef63d949ee2eb15d
> > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2225224
> > Commit-Queue: Bruce Dawson <brucedawson@chromium.org>
> > Reviewed-by: Henrik Andreasson <henrika@chromium.org>
> > Reviewed-by: Jamie Madill <jmadill@chromium.org>
> > Reviewed-by: Nico Weber <thakis@chromium.org>
> > Cr-Commit-Position: refs/heads/master@{#778924}
> 
> Bug: 920704, 1014701, 1021650, 1089996, 1095767
> Change-Id: I75e7653d57964e2929106e41b3f50594d3969e5f
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2249394
> Reviewed-by: Daniel Cheng <dcheng@chromium.org>
> Reviewed-by: Jesse McKenna <jessemckenna@google.com>
> Reviewed-by: Jamie Madill <jmadill@chromium.org>
> Commit-Queue: Bruce Dawson <brucedawson@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#780431}

TBR=dcheng@chromium.org,henrika@webrtc.org,thakis@chromium.org,brucedawson@chromium.org,henrika@chromium.org,jessemckenna@google.com,jmadill@chromium.org

Change-Id: If00e3865e66d9071189b2aca28f7541ecbdc6486
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 920704, 1014701, 1021650, 1089996, 1095767
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2255558
Reviewed-by: Bruce Dawson <brucedawson@chromium.org>
Reviewed-by: Daniel Cheng <dcheng@chromium.org>
Commit-Queue: Bruce Dawson <brucedawson@chromium.org>
Cr-Commit-Position: refs/heads/master@{#780467}


CrOS-Libchrome-Original-Commit: ed0697fcf0f958c1bc6643d911d99b1d9b52ed9b