Revert "Reland "Adding mojolpm fuzzer.""
This reverts commit cc205c1fd6f0fadbde73c71465f13c390e48546b.

Reason for revert: This looks to have broken linux-archive-rel.
I'm guessing DEPS are wrong.
https://ci.chromium.org/p/chromium/builders/ci/linux-archive-rel/24465
[48678/80681] CXX obj/chrome/common/importer/interfaces_mojolpm/profile_import.mojom-mojolpm.o
FAILED: obj/chrome/common/importer/interfaces_mojolpm/profile_import.mojom-mojolpm.o 
/b/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/chrome/common/importer/interfaces_mojolpm/profile_import.mojom-mojolpm.o.d -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_GNU_SOURCE -DCR_CLANG_REVISION=\"n344329-9284abd0-6\" -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -D_LIBCPP_ABI_UNSTABLE -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCXXABI_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_ENABLE_NODISCARD -DCR_LIBCXX_REVISION=375504 -DCR_SYSROOT_HASH=79a7783607a69b6f439add567eb6fcb48877085c -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DGLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_2_40 -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_40 -DENABLE_IPC_FUZZER -DWEBP_EXTERN=extern -DGOOGLE_PROTOBUF_NO_RTTI -DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -DHAVE_PTHREAD -DSK_CODEC_DECODES_PNG -DSK_CODEC_DECODES_WEBP -DSK_ENCODE_PNG -DSK_ENCODE_WEBP -DSK_HAS_PNG_LIBRARY -DSK_HAS_WEBP_LIBRARY -DSK_USER_CONFIG_HEADER=\"../../skia/config/SkUserConfig.h\" -DSK_GL -DSK_CODEC_DECODES_JPEG -DSK_ENCODE_JPEG -DSK_HAS_JPEG_LIBRARY -DSK_USE_LIBGIFCODEC -DSK_VULKAN_HEADER=\"../../skia/config/SkVulkanConfig.h\" -DSK_VULKAN=1 -DSK_SUPPORT_GPU=1 -DSK_GPU_WORKAROUNDS_HEADER=\"gpu/config/gpu_driver_bug_workaround_autogen.h\" -DVK_NO_PROTOTYPES -DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DUSE_CHROMIUM_ICU=1 -DU_ENABLE_TRACING=1 -DU_ENABLE_RESOURCE_TRACING=0 -DU_STATIC_IMPLEMENTATION -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_FILE -DUCHAR_TYPE=uint16_t -DWEBRTC_NON_STATIC_TRACE_EVENT_HANDLERS=0 -DWEBRTC_CHROMIUM_BUILD -DWEBRTC_POSIX -DWEBRTC_LINUX -DABSL_ALLOCATOR_NOTHROW=1 -DWEBRTC_USE_BUILTIN_ISAC_FIX=0 -DWEBRTC_USE_BUILTIN_ISAC_FLOAT=1 -DWEBRTC_USE_X11 -DHAVE_SCTP -DNO_MAIN_THREAD_WRAPPING -I../.. -Igen -I../../third_party/libwebp/src -I../../third_party/libyuv/include -I../../third_party/jsoncpp/source/include -I../../third_party/jsoncpp/generated -I../../third_party/protobuf/src -Igen/protoc_out -Igen -Igen/out/Release/gen -I../../third_party/protobuf/src -Igen -Igen/out/Release/gen -Igen -Igen/out/Release/gen -Igen -Igen/out/Release/gen -Igen -Igen/out/Release/gen -Igen -Igen/out/Release/gen -I../../third_party/skia -I../../third_party/libgifcodec -I../../third_party/vulkan/include -I../../third_party/skia/third_party/vulkanmemoryallocator -I../../third_party/vulkan/include -I../../third_party/boringssl/src/include -I../../third_party/icu/source/common -I../../third_party/icu/source/i18n -I../../third_party/perfetto/include -Igen/third_party/perfetto/build_config -Igen/third_party/perfetto -I../../third_party/webrtc_overrides -I../../third_party/webrtc -Igen/third_party/webrtc -I../../third_party/abseil-cpp -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -funwind-tables -fPIC -B../../third_party/binutils/Linux_x64/Release/bin -pthread -fcolor-diagnostics -fmerge-all-constants -fcrash-diagnostics-dir=../../tools/clang/crashreports -Xclang -mllvm -Xclang -instcombine-lower-dbg-declare=0 -fcomplete-member-pointers -m64 -march=x86-64 -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -Xclang -fdebug-compilation-dir -Xclang . -no-canonical-prefixes -Wall -Werror -Wextra -Wimplicit-fallthrough -Wthread-safety -Wextra-semi -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-unneeded-internal-declaration -Wno-undefined-var-template -Wno-ignored-pragma-optimize -Wno-implicit-int-float-conversion -Wno-final-dtor-non-final-class -Wno-builtin-assume-aligned-alignment -Wno-deprecated-copy -Wno-non-c-typedef-for-linkage -O2 -fno-ident -fdata-sections -ffunction-sections -fno-omit-frame-pointer -g0 -ftrivial-auto-var-init=pattern -fvisibility=hidden -Xclang -add-plugin -Xclang find-bad-constructs -Xclang -plugin-arg-find-bad-constructs -Xclang check-ipc -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -isystem../../build/linux/debian_sid_amd64-sysroot/usr/include/glib-2.0 -isystem../../build/linux/debian_sid_amd64-sysroot/usr/lib/x86_64-linux-gnu/glib-2.0/include -Wno-shorten-64-to-32 -std=c++14 -fno-exceptions -fno-rtti -nostdinc++ -isystem../../buildtools/third_party/libc++/trunk/include -isystem../../buildtools/third_party/libc++abi/trunk/include --sysroot=../../build/linux/debian_sid_amd64-sysroot -fvisibility-inlines-hidden -Wno-deprecated-declarations -c gen/chrome/common/importer/profile_import.mojom-mojolpm.cc -o obj/chrome/common/importer/interfaces_mojolpm/profile_import.mojom-mojolpm.o
In file included from gen/chrome/common/importer/profile_import.mojom-mojolpm.cc:17:
In file included from ../../chrome/common/importer/profile_import_process_param_traits.h:8:
In file included from ../../chrome/common/importer/profile_import_process_param_traits_macros.h:23:
In file included from ../../content/public/common/common_param_traits.h:24:
In file included from ../../content/public/common/common_param_traits_macros.h:15:
../../content/public/common/web_preferences.h:18:10: fatal error: 'third_party/blink/public/mojom/v8_cache_options.mojom.h' file not found
#include "third_party/blink/public/mojom/v8_cache_options.mojom.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

Original change's description:
> Reland "Adding mojolpm fuzzer."
> 
> This is a reland of 96b8d308d93e9f014d795ceb20474b6be9f42c12
> 
> Original change's description:
> > Adding mojolpm fuzzer.
> >
> > This adds code that generates libprotobuf-mutator based
> > structure-aware fuzzers as part of the mojom compilation process.
> > (changes in //mojo).
> >
> > It also adds a fuzzer for CodeCacheHost using this framework to demonstrate
> > how it will be used, and documentation explaining that fuzzer and how to use
> > this generator to write new fuzzers. (changes in //content/test).
> >
> > It finally includes a few changes to typemap and traits files that
> > were necessary to smooth over some inconsistencies in existing code
> > using mojo.
> >
> > Bug: 941849
> > Change-Id: I660a57bd90c0963bd9a0b8608c746cdb767edc98
> > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1978739
> > Commit-Queue: Mark Brand <markbrand@google.com>
> > Auto-Submit: Mark Brand <markbrand@google.com>
> > Reviewed-by: Peter Kasting <pkasting@chromium.org>
> > Reviewed-by: Daniel Cheng <dcheng@chromium.org>
> > Reviewed-by: Ted Meyer <tmathmeyer@chromium.org>
> > Reviewed-by: Oliver Chang <ochang@chromium.org>
> > Reviewed-by: Ken Rockot <rockot@google.com>
> > Cr-Commit-Position: refs/heads/master@{#746827}
> 
> Bug: 941849
> Change-Id: I01feb96401e1c9cbd3bbb2bf2a22ecc253d36b4e
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2087408
> Commit-Queue: Peter Kasting <pkasting@chromium.org>
> Reviewed-by: Peter Kasting <pkasting@chromium.org>
> Reviewed-by: Oliver Chang <ochang@chromium.org>
> Reviewed-by: Matthew Denton <mpdenton@chromium.org>
> Reviewed-by: Daniel Cheng <dcheng@chromium.org>
> Reviewed-by: David Roger <droger@chromium.org>
> Reviewed-by: Ken Rockot <rockot@google.com>
> Reviewed-by: Ted Meyer <tmathmeyer@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#751464}

TBR=pkasting@chromium.org,dcheng@chromium.org,droger@chromium.org,rockot@google.com,ochang@chromium.org,markbrand@google.com,mpdenton@google.com,tmathmeyer@chromium.org,mpdenton@chromium.org

Change-Id: If628a61fbfa40c17aa25752317263d7a79a4fb9f
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 941849
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2109280
Reviewed-by: Scott Violet <sky@chromium.org>
Commit-Queue: Scott Violet <sky@chromium.org>
Cr-Commit-Position: refs/heads/master@{#751526}


CrOS-Libchrome-Original-Commit: e4e1221c3df40dd779e13e8cf89811cad3be3853