Revert "Toolchain with d3dcompiler_old.dll included"
This reverts commit 6ddbac7f8b44ca9f4ef8adaf21229df9dec380a2.

Reason for revert: causing most ANGLE Windows tests to fail with:

[ RUN      ] D3DTextureTest.GlColorspaceNotAllowedForTypedD3DTexture/ES2_D3D9
../../third_party/angle/src/tests/test_utils/ANGLETest.cpp(57): error: Failed
ensureInitialized(138): LoadLibrary(d3dcompiler_47.dll) failed. GetLastError=126

e.g. https://ci.chromium.org/p/chromium/builders/luci.chromium.try/win-angle-rel/872

Original change's description:
> Toolchain with d3dcompiler_old.dll included
> 
> This switches Chromium for Windows to use a new toolchain package that
> is the same as the one landed in crrev.com/c/1450414 except that it
> includes both the new d3dcompiler_47.dll (from the 17763 SDK) and the
> old one (from the 17134 SDK). The two versions are so that most
> customers get the new version, with all of its bug fixes, while those
> who don't have proper UCRT installs will fall back to the old version.
> If there are enough of the latter then we can figure out a way to ship
> the UCRT beside chrome.exe so that they can get the fixes as well. If
> there are few enough of the latter then we can drop support for them.
> 
> This change also removes the UCRT from installs, reverting a portion of
> crrev.com/c/1450414, and adds d3dcompiler_old.dll to installs.
> 
> This toolchain package was created by copying d3dcompiler_47.dll from
> the win_sdk\Redist\D3D\{x64|x86} directories of the 17134 SDK to
> d3dcompiler_old.dll and repackaging the directory using the --repackage
> option of depot_tools\win_toolchain\package_from_installed.py.
> 
> Note that the logic in build\win\BUILD.gn for when to package up the
> UCRT was incorrect (it would try to package it for ARM64 component
> builds) and that is corrected as well in this change.
> 
> Angle can then use d3dcompiler_old.dll as a fallback, and record
> metrics about how often the fallback is used.
> 
> Bug: 920704
> Change-Id: Ida96d8b9247789a429519c50b0663f183d72c800
> Reviewed-on: https://chromium-review.googlesource.com/c/1461679
> Commit-Queue: Bruce Dawson <brucedawson@chromium.org>
> Reviewed-by: Jamie Madill <jmadill@google.com>
> Reviewed-by: Greg Thompson <grt@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#634207}

TBR=jmadill@google.com,brucedawson@chromium.org,grt@chromium.org

Change-Id: I0fbd1f963fdd4c3180715ff9eec38b7bb2c2bf4e
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 920704
Reviewed-on: https://chromium-review.googlesource.com/c/1481670
Reviewed-by: Jamie Madill <jmadill@chromium.org>
Commit-Queue: Jamie Madill <jmadill@chromium.org>
Cr-Commit-Position: refs/heads/master@{#634255}

CrOS-Libchrome-Original-Commit: 6f84ed3b4c8c26dc30642a91bb195943d1632cf3